SET search_path TO eleicao_2024;

SELECT nm_urna_candidato, nr_candidato FROM candidato
	WHERE nm_ue = 'UBERLÂNDIA'
	ORDER BY nm_urna_candidato DESC;
	
SELECT nm_candidato FROM candidato 
	WHERE sg_uf = 'AC' AND dt_nascimento < '01/01/1954';

SELECT nm_urna_candidato FROM candidato 
	WHERE nm_urna_candidato LIKE '%LULA%' OR 
	nm_urna_candidato LIKE '%BOLSONARO%';

SELECT nm_candidato, ds_grau_instrucao 
	FROM candidato cand, grau_instrucao grau
	WHERE cand.nm_ue = 'CASA BRANCA' AND cand.sg_uf = 'SP' 
	AND grau.cd_grau_instrucao = cand.cd_grau_instrucao;

SELECT nm_candidato, sg_partido
FROM candidato cand, partido part, genero gen, cargo carg
WHERE cand.cd_genero = gen.cd_genero
	AND gen.ds_genero = 'FEMININO'
	AND cand.cd_cargo = carg.cd_cargo 
	AND carg.ds_cargo = 'VEREADOR'
	AND cand.nr_partido = part.nr_partido 
	AND cand.nm_ue = 'CUIABÁ';

SELECT DISTINCT ds_ocupacao
	FROM candidato cand, ocupacao oc, partido part
		WHERE cand.cd_ocupacao = oc.cd_ocupacao 
		AND cand.nr_partido = part.nr_partido
		AND part.sg_partido = 'PSDB'
		AND sg_uf = 'BA';

SELECT NM_URNA_CANDIDATO, NR_CANDIDATO, SG_PARTIDO, DS_COLIGACAO
	FROM CANDIDATO, COLIGACAO, PARTIDO, CARGO
	WHERE UPPER(CANDIDATO.NM_UE) IN ('SÃO PAULO', 'ESPIRITO SANTO', 'RIO DE JANEIRO', 'BELO HORIZONTE') 
	AND CANDIDATO.CD_CARGO = CARGO.CD_CARGO 
	AND (CARGO.DS_CARGO = 'PREFEITO' OR CARGO.DS_CARGO ='VICE-PREFEITO') 
	AND CANDIDATO.NR_PARTIDO = PARTIDO.NR_PARTIDO 
	AND CANDIDATO.SQ_COLIGACAO = COLIGACAO.SQ_COLIGACAO;

SELECT NM_CANDIDATO, SG_PARTIDO, DS_TIPO_BEM_CANDIDATO, VR_BEM_CANDIDATO
	FROM CANDIDATO, BEM_CANDIDATO, CARGO, PARTIDO
	WHERE CANDIDATO.NM_UE = 'SÃO PAULO' 
		AND CANDIDATO.CD_CARGO = CARGO.CD_CARGO 
		AND CARGO.DS_CARGO = 'PREFEITO' 
		AND	CANDIDATO.NR_PARTIDO = PARTIDO.NR_PARTIDO 
		AND CANDIDATO.SQ_CANDIDATO = BEM_CANDIDATO.SQ_CANDIDATO;

SELECT nm_candidato, dt_nascimento
	FROM candidato
	WHERE dt_nascimento IS NULL;

SELECT NM_CANDIDATO,SG_PARTIDO,DS_ESTADO_CIVIL,DS_OCUPACAO 
	FROM CANDIDATO C, PARTIDO P, OCUPACAO O, GENERO G, ESTADO_CIVIL E
	WHERE  DS_GENERO = 'FEMININO' 
		AND C.CD_GENERO = G.CD_GENERO 
		AND C.NR_PARTIDO = P.NR_PARTIDO 
		AND C.CD_ESTADO_CIVIL=E.CD_ESTADO_CIVIL 
		AND C.CD_OCUPACAO=O.CD_OCUPACAO 
		AND UPPER(NM_UE) IN ('BELO HORIZONTE ','RIO DE JANEIRO','SÃO PAULO','VITÓRIA');

SELECT NM_CANDIDATO, SG_PARTIDO
	FROM CANDIDATO, PARTIDO, CARGO
	WHERE CANDIDATO.NM_UE = 'ROMARIA' 
	AND CANDIDATO.CD_CARGO = CARGO.CD_CARGO 
	AND CARGO.DS_CARGO = 'PREFEITO' 
	AND CANDIDATO.NR_PARTIDO = PARTIDO.NR_PARTIDO;

SELECT DS_ESTADO_CIVIL
	FROM CANDIDATO, ESTADO_CIVIL, COR_RACA
	WHERE CANDIDATO.CD_COR_RACA = COR_RACA.CD_COR_RACA 
	AND COR_RACA.DS_COR_RACA = 'PRETA' 
	AND CANDIDATO.CD_ESTADO_CIVIL = ESTADO_CIVIL.CD_ESTADO_CIVIL 
	AND CANDIDATO.NM_UE = 'UBERLÂNDIA';